jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build docs
        uses: athackst/mkdocs-simple-plugin
        with:
          # (optional) Specify branch 
          publish_branch: gh-pages 
          # (optional) The URL of the repository the docs should point to
          repo_url: https://github.com/scotthadzik/tb3_demo
          # (optional) The name of the site
          site_name: owner/repository 
          # (optional) The URL of the site
          # site_url: https://owner.github.io/repository 
          # (optional) The edit URI
          edit_uri: edit/main/
          # (optional) Specify a google analytics key 
          google_analytics: UA-XXXXXXX
          # (optional) Specify a different theme [mkdocs|readthedocs|material]
          theme: material
          # (optional) Load a configuration file from a string
          config: "{additional_css: value}"
          # (optional) Version or alias.  Specify multiple aliases with space
          # example: version: v0.1.0 latest
          version: latest
          # (optional) The version that will be served by the root of your site
          default_version: latest
          # (optional) Whether to push the docs to the remote branch
          push: 1